MODEL_PARAMETERS:
  T_INITIAL: -21
  T_FINAL: 7200

HEMODYNAMICS:
  S_BLOOD_VOLUME: 5000
  S_BLOOD_PRESSURE: 65
  K_BASELINE_BLOOD_PRESSURE: 0.001
  K_BLOOD_PRESSURE_NO: 1.0e-07
  K_URINATE: 0.01

COAGULATION:
  S_RBC: 5.0e9
  K_BASELINE_RBC: 4.01127e-6
  S_INACTIVE_COAG_FACTOR: 1.0e8
  S_INACTIVE_ANTI_COAG: 4.0e6
  S_ACTIVE_ANTI_COAG: 1.0e3
  S_PLATELETS: 3
  K_BASELINE_PLATELETS: 0.000120338
  RBC_INFUSION_BONUS_CONC: 1.44
  PLASMA_INFUSION_COAG_BONUS: 1.55
  PLATELET_INFUSION_BONUS_CONC: 3.67
  D_ACTIVE_COAG_FACTOR: 0.693314718
  D_CLOT: 1.0e-5
  K_ACTIVE_COAG_FACTOR_ACTIVE_ANTI_COAG_ENHANCE: 0.001
  K_ACTIVE_COAG_FACTOR_ACTIVE_ANTI_COAG_COLLIDE: 0.001
  K_PLATELET_SOURCE_ENHANCE: 0.001
  K_COAG_FACTOR_ACTIVATION_TRAUMA: 1.0e-7
  K_INACTIVE_ANTI_COAG_ACTIVE_COAG_FACTOR: 1.0e-7
  K_CLOT: 1.0e-9
  K_CLOT_RBC: 1.0e-7
  K_BLEED_TRAUMA: 12
  K_BLEED_CONTROL: 5.0e-4
  K_FIBRINOLYSIS: 0.001
  ACTIVECOAGFACTOR_PORTION_OF_CLOT_CONVERTER: 1
  PLATELETS_PORTION_OF_CLOT_CONVERTER: 1

INFLAMMATION:
  ALPHA_DAMP_SENS: 1
  ALPHA_TNF_PRODUCTION: 1
  ALPHA_1_PRODUCTION: 1
  ALPHA_6_PRODUCTION: 1
  ALPHA_10_PRODUCTION: 1
  K_B_T_MA0: 0.001
  TRAUMA_CELL_ACTIVATION_SCALE: 10
  S_MR: 80000
  D_MO_BLOOD: 0.000240676
  D_MR_TIS_LUNG: 1.58253e-5
  D_MA_TIS_LUNG: 6.87646e-5
  K_MO_SOURCE_ENHANCE: 1.0e-2
  K_B_T_NA0: 0.001
  S_NR: 2500000
  D_NU_BLOOD: 0.001925409
  D_NU_TIS_LUNG: 0.000240676
  K_NU_SOURCE_ENHANCE: 1.0e-2
  S_EPRL: 2.016e10
  S_EPRS: 2.016e10
  D_EP: 7.91264e-6
  GUISCALEIL10: 5000
  GUISCALEIL6: 20000
  GUISCALETNF: 18000
  GUISCALE_DAMAGE: 0
  GUISCALEIL1: 100
  DAMP_LOAD: 0.001
  K_EP_DAMP: 1
  X_EP_DAMP: 78049.8
  XDAMP_EP: 100
  KTNFM: 1.0e7
  KTNFN: 1.0e7
  D_TNF: 0.040773364
  KMTNF: 10
  KNTNF: 1.0e-4
  K_EP_TNF: 1.0e-7
  XMTNF: 10
  XNTNF: 10
  X_EP_TNF: 20
  XTNF_EP: 1.0e-5
  XTNFN: 1
  XTNFM: 1
  K1M: 1.0e5
  K1N: 1.0e5
  K1EP: 1.0e5
  D_1: 0.11552453
  KM1: 100
  KN1: 1.0e-4
  K_EP1: 1.0e-7
  X1N: 1
  X1M: 1
  X1EP: 2
  XM1: 0.1
  XN1: 0.1
  X_EP1: 1.0e-5
  K6M: 0.01
  K6N: 0.01
  K6EP: 5.0e-7
  D_6: 0.002888113
  KM6: 1.0e-14
  KN6: 1.0e-14
  K_EP6: 1.0e-10
  X_EP6: 500
  XM6: 1
  XN6: 1
  X6EP: 1
  S_10: 10
  K10M: 1000
  K10N: 1000
  K10EP: 1000
  KM10: 1.0e-6
  KN10: 1.0e-6
  K_EP10: 1.0e-6
  K_BASELINE_IL10: 0.003850818
  XEP10: 1.0e-14
  XM10: 2.5e-7
  XN10: 2.5e-7
  KINOSM: 1
  KINOSN: 1
  KINOSEP: 1
  XINOS10: 1
  XINOSNO: 1
  XENOSPE: 25
  D_ENOS: 1.0e-5
  D_INOS: 1.0e-5
  D_NO: 0.002062938
  SOURCE_ENOS: 0.001
  K_NO_INOS: 0.1
  K_NO_ENOS: 0.1
  K_NO_MA: 0.1
  K_NO_NA: 0.1
  K_NO_EP: 0.1
  V_LECF: 500
  V_SECF: 5000
  RECOVERY_SLOWNESS: 10000
  MAX_ISS: 75
  K_B_T_MA_L: 0.4
  K_B_T_NA_L: 0.4
  O2SAT0: 98
  VENT_PAR1: 2.5e6
  VENT_PAR2: 1.0e-5
  VENT_PAR3: 1.0e-4
  ML_MIN: 0
  PG_PER_MIN_PER_ML_PER_CELLS: 1
  ONE_PER_ML: 1
  PG_PER_CELLS_PER_MIN: 1
  UNIT_ML: 1
  ONE_PER_MIN: 0
  K_COAG_FACTOR_ACTIVATION_IL6: 1.0e-7
  KM_COAG: 1.0e-4
  XM_COAG: 1.0e-5
  KN_COAG: 1
  XN_COAG: 1.0e-9
  K_EP_COAG: 1.0e-4
  X_EP_COAG: 1.0e-5
  K_DAMAGE_IL6: 1.25
  X_DAMAGE_IL6: 90
  IL6_DAMAGE_THRESHOLD: 10
  USE_BLOOD_IL6_ONLY: 1
  K_DAMAGE_O2SAT: 2.5
  O2SAT_DAMAGE_THRESHOLD: 93
  MAX_O2SAT: 98
  K_DAMAGE_BP: 2.5
  X_DAMAGE_BP: 37
  BP_DAMAGE_THRESHOLD: 70
  K_DAMAGE_TRAUMA: 3.75
  DAMAGE_DEATH_THRESHOLD: 276.53

INFUSION_SETTINGS:
  MIN_PLASMA_DOSE: 100
  MIN_FLUID_DOSE: 100
  MIN_RBC_DOSE: 100
  MIN_PLATELET_DOSE: 100
  TON_PLASMA_INFUSION1: 0
  T_PLASMA_INFUSION_DURATION1: 0
  PLASMA_DOSE1: 0
  TON_PLASMA_INFUSION2: 0
  T_PLASMA_INFUSION_DURATION2: 0
  PLASMA_DOSE2: 0
  TON_PLASMA_INFUSION3: 0
  T_PLASMA_INFUSION_DURATION3: 0
  PLASMA_DOSE3: 0
  TON_PLASMA_INFUSION4: 0
  T_PLASMA_INFUSION_DURATION4: 0
  PLASMA_DOSE4: 0
  TON_PLASMA_INFUSION5: 0
  T_PLASMA_INFUSION_DURATION5: 0
  PLASMA_DOSE5: 0
  TON_PLASMA_INFUSION6: 0
  T_PLASMA_INFUSION_DURATION6: 0
  PLASMA_DOSE6: 0
  TON_PLASMA_INFUSION7: 0
  T_PLASMA_INFUSION_DURATION7: 0
  PLASMA_DOSE7: 0
  TON_PLASMA_INFUSION8: 0
  T_PLASMA_INFUSION_DURATION8: 0
  PLASMA_DOSE8: 0
  TON_PLASMA_INFUSION9: 0
  T_PLASMA_INFUSION_DURATION9: 0
  PLASMA_DOSE9: 0
  TON_PLASMA_INFUSION10: 0
  T_PLASMA_INFUSION_DURATION10: 0
  PLASMA_DOSE10: 0
  TON_FLUID_INFUSION1: 0
  T_FLUID_INFUSION_DURATION1: 0
  FLUID_DOSE1: 0
  TON_FLUID_INFUSION2: 0
  T_FLUID_INFUSION_DURATION2: 0
  FLUID_DOSE2: 0
  TON_FLUID_INFUSION3: 0
  T_FLUID_INFUSION_DURATION3: 0
  FLUID_DOSE3: 0
  TON_FLUID_INFUSION4: 0
  T_FLUID_INFUSION_DURATION4: 0
  FLUID_DOSE4: 0
  TON_FLUID_INFUSION5: 0
  T_FLUID_INFUSION_DURATION5: 0
  FLUID_DOSE5: 0
  TON_FLUID_INFUSION6: 0
  T_FLUID_INFUSION_DURATION6: 0
  FLUID_DOSE6: 0
  TON_FLUID_INFUSION7: 0
  T_FLUID_INFUSION_DURATION7: 0
  FLUID_DOSE7: 0
  TON_FLUID_INFUSION8: 0
  T_FLUID_INFUSION_DURATION8: 0
  FLUID_DOSE8: 0
  TON_FLUID_INFUSION9: 0
  T_FLUID_INFUSION_DURATION9: 0
  FLUID_DOSE9: 0
  TON_FLUID_INFUSION10: 0
  T_FLUID_INFUSION_DURATION10: 0
  FLUID_DOSE10: 0
  TON_RBC_INFUSION1: 0
  T_RBC_INFUSION_DURATION1: 0
  RBC_DOSE1: 0
  TON_RBC_INFUSION2: 0
  T_RBC_INFUSION_DURATION2: 0
  RBC_DOSE2: 0
  TON_RBC_INFUSION3: 0
  T_RBC_INFUSION_DURATION3: 0
  RBC_DOSE3: 0
  TON_RBC_INFUSION4: 0
  T_RBC_INFUSION_DURATION4: 0
  RBC_DOSE4: 0
  TON_RBC_INFUSION5: 0
  T_RBC_INFUSION_DURATION5: 0
  RBC_DOSE5: 0
  TON_RBC_INFUSION6: 0
  T_RBC_INFUSION_DURATION6: 0
  RBC_DOSE6: 0
  TON_RBC_INFUSION7: 0
  T_RBC_INFUSION_DURATION7: 0
  RBC_DOSE7: 0
  TON_RBC_INFUSION8: 0
  T_RBC_INFUSION_DURATION8: 0
  RBC_DOSE8: 0
  TON_RBC_INFUSION9: 0
  T_RBC_INFUSION_DURATION9: 0
  RBC_DOSE9: 0
  TON_RBC_INFUSION10: 0
  T_RBC_INFUSION_DURATION10: 0
  RBC_DOSE10: 0
  TON_PLATELET_INFUSION1: 0
  T_PLATELET_INFUSION_DURATION1: 0
  PLATELET_DOSE1: 0
  TON_PLATELET_INFUSION2: 0
  T_PLATELET_INFUSION_DURATION2: 0
  PLATELET_DOSE2: 0
  TON_PLATELET_INFUSION3: 0
  T_PLATELET_INFUSION_DURATION3: 0
  PLATELET_DOSE3: 0
  TON_PLATELET_INFUSION4: 0
  T_PLATELET_INFUSION_DURATION4: 0
  PLATELET_DOSE4: 0
  TON_PLATELET_INFUSION5: 0
  T_PLATELET_INFUSION_DURATION5: 0
  PLATELET_DOSE5: 0
  TON_PLATELET_INFUSION6: 0
  T_PLATELET_INFUSION_DURATION6: 0
  PLATELET_DOSE6: 0
  TON_PLATELET_INFUSION7: 0
  T_PLATELET_INFUSION_DURATION7: 0
  PLATELET_DOSE7: 0
  TON_PLATELET_INFUSION8: 0
  T_PLATELET_INFUSION_DURATION8: 0
  PLATELET_DOSE8: 0
  TON_PLATELET_INFUSION9: 0
  T_PLATELET_INFUSION_DURATION9: 0
  PLATELET_DOSE9: 0
  TON_PLATELET_INFUSION10: 0
  T_PLATELET_INFUSION_DURATION10: 0
  PLATELET_DOSE10: 0